# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hello-service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "hello-service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import hello_pb2 as hello__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13hello-service.proto\x12\x0chelloService\x1a\x0bhello.proto"+\n\x0cHelloRequest\x12\x1b\n\x05hello\x18\x01 \x01(\x0b\x32\x0c.hello.Hello"D\n\x12MultiHelloResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x1f\n\tgreetings\x18\x02 \x03(\x0b\x32\x0c.hello.Hello2^\n\x0cHelloService\x12N\n\nmultiHello\x12\x1a.helloService.HelloRequest\x1a .helloService.MultiHelloResponse"\x00(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hello_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HELLOREQUEST"]._serialized_start = 50
    _globals["_HELLOREQUEST"]._serialized_end = 93
    _globals["_MULTIHELLORESPONSE"]._serialized_start = 95
    _globals["_MULTIHELLORESPONSE"]._serialized_end = 163
    _globals["_HELLOSERVICE"]._serialized_start = 165
    _globals["_HELLOSERVICE"]._serialized_end = 259
# @@protoc_insertion_point(module_scope)
