# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_service_pb2 as user__service__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserGetterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserById = channel.unary_unary(
                '/userService.UserGetter/GetUserById',
                request_serializer=user__service__pb2.UserRequestById.SerializeToString,
                response_deserializer=user__service__pb2.UserDetailsResponse.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/userService.UserGetter/GetUserByUsername',
                request_serializer=user__service__pb2.UserRequestByUsername.SerializeToString,
                response_deserializer=user__service__pb2.UserDetailsResponse.FromString,
                _registered_method=True)
        self.GetUsersMatchingUsername = channel.unary_stream(
                '/userService.UserGetter/GetUsersMatchingUsername',
                request_serializer=user__service__pb2.UserRequestByUsername.SerializeToString,
                response_deserializer=user__service__pb2.UserDetailsResponse.FromString,
                _registered_method=True)


class UserGetterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersMatchingUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserGetterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserById,
                    request_deserializer=user__service__pb2.UserRequestById.FromString,
                    response_serializer=user__service__pb2.UserDetailsResponse.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=user__service__pb2.UserRequestByUsername.FromString,
                    response_serializer=user__service__pb2.UserDetailsResponse.SerializeToString,
            ),
            'GetUsersMatchingUsername': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUsersMatchingUsername,
                    request_deserializer=user__service__pb2.UserRequestByUsername.FromString,
                    response_serializer=user__service__pb2.UserDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userService.UserGetter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('userService.UserGetter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserGetter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userService.UserGetter/GetUserById',
            user__service__pb2.UserRequestById.SerializeToString,
            user__service__pb2.UserDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userService.UserGetter/GetUserByUsername',
            user__service__pb2.UserRequestByUsername.SerializeToString,
            user__service__pb2.UserDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersMatchingUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/userService.UserGetter/GetUsersMatchingUsername',
            user__service__pb2.UserRequestByUsername.SerializeToString,
            user__service__pb2.UserDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
